### ISSUE TITLE
GL Support

### ISSUE THREAD

**Issue by 641i130** [rafi1212122/SCHALE.GameServer#14]
I've done research/implementation already on creating a global private server (including asset hosting and log black-hole-ing).

Please reach out to me, I would like to contribute and provide my research. I'm a bit stuck on implementing the gateway handling, but I'm very close...

Matrix:
`caret:m.sif.moe`

Discord:
`caretchara`

Love the research you've all done! You all are awesome!

---
(chatgpt translation)

我已经完成了关于创建全球私有服务器（包括资产托管和日志黑洞）的研究和实现。

请联系我，我愿意贡献并提供我的研究。我在实现网关处理方面有点卡住了，但我已经非常接近成功了……

Matrix:
`caret:m.sif.moe`

Discord:
`caretchara`

非常喜欢你们所有的研究！你们都很棒！

**Comment by YikeNick** [comment]
what‘’s that mean about.....“global private server”

**Comment by YikeNick** [comment]
is that mean ba International server？

**Comment by 641i130** [comment]
Yeah, same thing lol

**Comment by YikeNick** [comment]
> 是的，同样的事情哈哈
cool！ Are you going to make this project public, in fact, I'm a high school student from China, my Japanese is not very good, and I can't read most of the things on this server

**Comment by 641i130** [comment]
Ask me on discord or matrix please. Delete your comments here, I want this thread to look cleaner.

**Comment by YikeNick** [comment]
> 请在 discord 或 matrix 上问我。在这里删除您的评论，我希望这个线程看起来更干净。

Can you give me your email address, it's very inconvenient to use X in China, and then you can delete these, including this one, please ：

**Comment by Maren0000** [comment]
My Github fork has a branch with experimental support for GL. It's not perfect and requires a bit of manual work, but it's enough to get to the main menu.

I've sent an FR on Discord if you want to discuss some more on how it works.

**Comment by YikeNick** [comment]
> 我的 Github 分支有一个对 GL 的实验性支持的分支。它并不完美，需要一些手动工作，但足以进入主菜单。
> 
> 我已经在 Discord 上发送了 FR，如果您想进一步讨论它的工作原理。

Does this private server rely on official servers? Isn't it that these are no longer available after the official server stops running

**Comment by YikeNick** [comment]
I tried adding your X, but it shows blocked

**Comment by YikeNick** [comment]
can I get you discord？：

**Comment by YikeNick** [comment]
> 我可以让你不和谐吗？

我想问一些问题还有一些关于这个项目的事情

**Comment by 641i130** [comment]
Re-read my post, it's already there.
