### ISSUE TITLE
2 q

### ISSUE THREAD

**Issue by YikeNick** [rafi1212122/SCHALE.GameServer#4]
First of all, I want to express my sincere gratitude for your project. You guys are truly a blessing. As a high school student with limited English proficiency, I apologize for any inaccuracies in my translation. Here are the two questions I'd like to ask you:

1.Will the locally hosted server allow us to experience the complete game content, such as "Memory Hall" and "Storyline," after connecting in future updates?
2.Can this locally hosted server be used with the "Blue Archive China Server?"

Thank you for understanding my limited English ability and for taking the time to answer my questions.

**Comment by raphaeIl** [comment]
1. While we will continue to update the server with more features in the future, I can not guaranteed you that you will be able to experience the "completely game content"
2. No, currently it does not work on CN
